### ISSUE TITLE
Simplification de la gestion des layers

### ISSUE THREAD

**Issue by tconstans** [2p2r/velobs_web#103]
Hello,

L'idée est de pouvoir réutiliser une carte osm personnalisée (par ex celle de LVV http://lavilleavelo.org/carte/ )

**Comment by gerald2545** [comment]
permettre de définir les layers qu'on veut voir afficher dans le champ "carte" de velobs au niveau de key.js et non directement en dur dans le code source

**Comment by gerald2545** [comment]
les layers sont maintenant définis dans le fichier lib/js/key.js.template, à copier dans lib/js/key.js
