### ISSUE TITLE
Interface d'admin: pouvoir faire des group by sur les colonnes

### ISSUE THREAD

**Issue by tconstans** [2p2r/velobs_web#105]
Par exemple n'afficher que les observations d'une commune en particulier, ou avec un état / catégorie particulier (à minima pouvoir filtrer observations déjà modérées / observations à modérer)

**Comment by gerald2545** [comment]
en effet, ce serait une bonne amélioration.
A l'heure actuelle, la seule possibilité pour faciliter ça est d'exporter le fichier csv des observations (avec le bouton "Télécharger la liste des observation") et de traiter dans un tableur (qui contient un lien vers l'interface d'administration de chaque observation)
![image](https://user-images.githubusercontent.com/10177830/37224514-0b7f9210-23d4-11e8-91d1-728014b3fb0c.png)

SInon, avec la modération par cartographie, on pourrait rajouter une combobox permettant de n'afficher que les observations A modérer

**Comment by gerald2545** [comment]
dans l'onglet carte de l'interface d'administration, ajout d'un filtre sur les priorités
![image](https://user-images.githubusercontent.com/10177830/37233532-d7f55c7a-23f3-11e8-9a06-59585e707283.png)
