### ISSUE TITLE
Connaitre sa version de VelObs installé

### ISSUE THREAD

**Issue by Foxiiiii** [2p2r/velobs_web#119]
Bonjour,

je n'arrive pas à trouver l'endroit où est affichée la version de VelObs installée.

Cordialement

**Comment by gerald2545** [comment]
Hi Foxiiiii, for the moment, you don't have an easy way to know that.
I will add a variable to store the source version and inject it in the title of the web page.
OK for you?

**Comment by Foxiiiii** [comment]
It will be perfect.

**Comment by gerald2545** [comment]
For the moment, I didn't find a clean way to do that.
it's hardcoded in the html title tag of the index.php file....to be modified for each release
