### ISSUE TITLE
envoyer un mail aux modérateurs Asso quand la Collectivité édite une observation

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#12]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 09:24 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/12_

----

**Comment by gerald2545** [comment]
quand un pole edite une observation, on ajoute les modérateurs dans les destinataires : 
$sql3 = "SELECT mail_users FROM users WHERE (usertype_id_usertype = 2 AND territoire_id_territoire = ".$territoire_id_territoire.") **OR (usertype_id_usertype = 4 AND num_pole = ".$id_pole.")**";

a faire pour la comcom

**Comment by gerald2545** [comment]
mails envoyés à  : 
- $whereClause = "u.usertype_id_usertype = 1 OR (u.usertype_id_usertype = 4 AND u.num_pole = ".$arrayObs['pole_id_pole'].")"; dans updatePoiPoleTechCarto
- $whereClause = "u.usertype_id_usertype = 1 OR (u.usertype_id_usertype = 4 AND u.num_pole = ".$arrayObs['pole_id_pole'].")"; dans updatePoiComcomCarto
- $whereClause = "u.usertype_id_usertype = 1 OR (u.usertype_id_usertype = 4 AND u.num_pole = ".$arrayObs['pole_id_pole'].")"; dans updatePoi si c'est la comcom ou un pole qui a fait une modification
-
