### ISSUE TITLE
Nombre de commentaire faux suite maj 1.5.2

### ISSUE THREAD

**Issue by adavapaysdaix** [2p2r/velobs_web#170]
Bonjour,
Suite à la maj cette après-midi, il y a un petit bug dans l'interface admin/modo, toutes les observations ont vu leur compteur de commentaire augmenté de 1.  (si 0, passé à 1 // si 3, passé à 4 par exemple)
![capture](https://user-images.githubusercontent.com/38887262/39480601-fbbe21ca-4d68-11e8-921b-3468e6c6b0df.PNG)

**Comment by gerald2545** [comment]
thank you @ldesp for the pull request
