### ISSUE TITLE
Problème de mini-carte dans la modération des observations

### ISSUE THREAD

**Issue by adavapaysdaix** [2p2r/velobs_web#171]
Bonjour,
Dans le panneau qui s'ouvre pour modérer une observation il y a une mini-carte de localisation. Celle-ci est différente de la carte principale, elle n'est pas à jour. 
La carte principale provient d'openstreetmap (mapnik ?), pas de soucis mais la mini-carte provient de hikebike ? qui n'est pas à jour. Est-il possible mettre OSM dans les 2 cas ? 
Merci.

![1](https://user-images.githubusercontent.com/38887262/39480876-dec1d688-4d69-11e8-9244-2cf4b4271c74.PNG)

**Comment by gerald2545** [comment]
I modified the defaut map for that in key.js.template.
note that you can define this admin map as you want by ovveriding the variable adminMapForPoi in key.js (look at key.js.template for map configurations examples)
