### ISSUE TITLE
Liste observations vide aléatoirement 

### ISSUE THREAD

**Issue by fmalard** [2p2r/velobs_web#176]
https://velobs08.ouvaton.org
je coche pour voir des ou toutes les observations . OK
https://velobs08.ouvaton.org/admin.php
  login OK, j'ai accès au catégories, sous-catégories, utilisateurs 
mais la liste des observations est vide et je n'ai que le fond de carte sans les observations.

D'autres fois, cela fonctionne. 
Time out pour l'accès à la base de données ?
François

**Comment by gerald2545** [comment]
j'ai réussi à reproduire avec le compte gerald (admin)...mais en effet, ça semble aléatoire.
tu as régulièrement des erreurs de redirection vers admin.php, avec un code retour 302 (Moved temporarily) : 
![image](https://user-images.githubusercontent.com/10177830/40102040-a9f74fce-58e9-11e8-88c3-927d8b2979b7.png)

je ne l'explique pas, on ne rencontre pas ce problème sur notre instance...

Il y a aussi (problèmes liés?) des problèmes quelquefois à la création de la session php....
je regarde si je trouve des infos.

Pour info, je me suis permis de modifier la version de php utilisée pour votre instance, pour la passer de 5.6 en 7.2

**Comment by gerald2545** [comment]
au fait, les logs du serveur web ne semblent pas activés. Tu peux regarder pour qu'on y accède STP, ça facilitera sans doute grandement la tâche

**Comment by poulagah** [comment]
salut l'équipe vélobs,
problème similaire rencontré : la liste des observations validées à la suite d'une modération n'est pas visible sur la page publique, par contre sous le compte administrateur elles apparaissent.

les journaux d'erreurs sont plutôt bavards et racontent avec récurrence : 
```
[:error] [pid 31998] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, null given in /var/www/velobs/lib/php/mysql2i.class.php on line 408
[:error] [pid 31998] PHP Warning:  mysqli_data_seek() expects parameter 1 to be mysqli_result, null given in /var/www/velobs/lib/php/mysql2i.class.php on line 425
[:error] [pid 31998] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in /var/www/velobs/lib/php/mysql2i.class.php on line 435
```
ça ressemblerait à un soucis de scoping ?

```
[:error] [pid 31998] PHP Notice:  Undefined index: id_language in /var/www/velobs/index.php on line 67
[:error] [pid 31998] PHP Notice:  Undefined index: nom in /var/www/velobs/index.php on line 68
```

on relève également ça concernant les stats, mais probable que ce soit sans conséquences pour le problème qui nous concerne : 

```
[:error] PHP Notice:  Undefined index: type in /var/www/velobs/lib/php/public/getJsonStats.php on line 29, 33, 38, 44
```
pour respectivement concerner ces lignes : 		
```
if ($_SESSION ["type"] == 2) { // is communaute de communes
} elseif ($_SESSION ["type"] == 3) { // is pole technique
} elseif ($_SESSION ["type"] == 4) { // is moderateur
error_log(date("Y-m-d H:i:s") . " - getJsonStats.php ".$_SESSION["type"].", ". $sqlGetStats ."\n", 3, LOG_FILE);
```

si besoin :)

**Comment by gerald2545** [comment]
Bonjour @poulagah,
j'ai l'impression que ce n'est pas le même problème. Tu travailles sr quelle instance de velobs? tu peux me donner un lien?
Pour les logs que tu cites, ils ne m'ont pas l'air "anormaux", code à revoir un peu, mais j'ai les mêmes.

**Comment by gerald2545** [comment]
vu avec François,
depuis plusieurs jours, plus de problème.
Le support ouvaton avait été contacté, sans retour, mais plus de problème depuis. Ils ont peut-être modifié une config
ou alors le fait que je passe la version de php en 7.2 au lieu de 5.4 sur le site de François?

**Comment by poulagah** [comment]
salut @gerald2545 , qu'entends-tu par instance ? ce serait pour mettre en place sur la métropole de Grenoble, je n'ai pas eu le temps de m'y remettre pour trouver les causes,
pour l'heure voici l'adresse de la version d'essai https:// 91 .68 .195 .122 :88, si vous avez des pistes :)

**Comment by gerald2545** [comment]
@poulagah 
l'instance de Grenoble, ça me va, c'est ce que je voulais savoir (plus agréable de savoir à qui on cause ;))
peux-tu STP ouvrir une nouvelle issue STP, ces prolèmes ne sont pas liés
j'ai en effet regardé, rien ne m'a sauté aux yeux...
peux-tu m'écrire à gerald.salin@gmail.com STP, pour échanger en direct (j'aurais besoin d'un compte admin pour accéder aux observations)

A+
Gérald
