### ISSUE TITLE
optimiser la modération de l'ajout de photos

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#18]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 10:07 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/18_

----

Quand un.e cycliste ajoute une photo à une observation, les modérateurs ne sont pas notifiés (il faudrait envoyer un mail).

On pourrait accepter les ajouts de photo sans modération par défaut (modération à posteriori). Et changer de politique si il y a des abus.

La modération des commentaires et des photos supplémentaires n'est pas possible depuis la popup de modération :/ peu de modérateurs pensent à aller voir les champs tout à droite du tableau.

**Comment by bikepunk** [comment]
<a href="https://github.com/gerald2545"><img src="https://avatars.githubusercontent.com/u/10177830?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gerald2545](https://github.com/gerald2545)**
_Monday Oct 31, 2016 at 19:52 GMT_

----

Perso, je reçois bien un mail quand une photo est ajoutée (par contre l'adresse de modération n'est pas correct) : 
Bonjour !
Une nouvelle photo a été ajoutée sur le POI n°1580. Veuillez vous connecter à l'interface d'administration pour le modérer.
Lien vers la modération : http://velobs.2p2r.org/admin.html?id 80
Cordialement, l'application vélo :)

**Comment by gerald2545** [comment]
sur nouvelle photo, un mail est envoyé à MAIL_ALIAS_OBSERVATION_ADHERENTS et aux mails $sql = "SELECT mail_users FROM users WHERE usertype_id_usertype = 4 AND num_pole = ".$pole_id_pole si ce n'est pas un modérateur qui a ajouté la photo

**Comment by gerald2545** [comment]
sur velobs/lib/php/mobile/velObsRecord.php,
envoie de mails aux admin et moderateurs de pole : 
$sql = "SELECT mail_users FROM users WHERE usertype_id_usertype = 1 OR (usertype_id_usertype = 4 AND num_pole = ".$pole_id_pole.")";

**Comment by gerald2545** [comment]
#55 boutons ajoutés sur l'interface de modération

**Comment by gerald2545** [comment]
$subject = 'Photo à modérer sur l\'observation n°'.$arrayObs['id_poi'];
                    $message = 'Bonjour !
velobs/lib/php/admin/uploadPhotoSuppPublic.php. Mail pus complet et envoyé aux admins + moderateur du pole si personne n'est connecté (pas de SESSION[user])
Une nouvelle photo a été ajoutée sur l\'observation n°'.$arrayObs['id_poi'].'. Veuillez vous connecter à l\'interface d\'administration pour le modérer.
Lien vers la modération : '.URL.'/admin.php?id='.$arrayObs['id_poi']."\n".$arrayDetailsAndUpdateSQL['detailObservationString'].'
Cordialement, l\'application velobs:)';
                        // boucle sur les administrateurs #pole# généraux de l'association
                        $sql = "SELECT mail_users FROM users WHERE usertype_id_usertype = 1 OR (usertype_id_usertype = 4 AND num_pole = ".$arrayObs['pole_id_pole'].")";
                        $result = mysql_query($sql);
                        while ($row = mysql_fetch_array($result)) {
                            $to = $row['mail_users'];
							sendMail($to,$subject,$message);
                        }
