### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by tconstans** [2p2r/velobs_web#182]
Hello,

When moderating an issue, the fields "reponse de la collectivité" et "réponse du responsable de pole" are not editable.

We can only add a "final comment".

We tried with 2 accounts: responsable de pole and admin.

Version is 1.5.2

Thanks for the feedback

**Comment by gerald2545** [comment]
below, paragraph **extracted from install.odt, 3. Installation**, is this answering your question?
Editer lib/js/key.js si vous souhaitez personnaliser votre installation (le lib/js/key.js.template sera écrasé à chaque mise à jour, pas lib/js/key.js): 
Définir les cartes que vous voulez voir afficher sur l’interface publique. Par défaut, 2 cartes sont créées (cf mapnik et osmcyclemap), mais vous pouvez en créer d’autres. Il suffit ensuite d’ajouter une référence de ces cartes dans le tableau « mapLayersArray »
modifier la variable TF_key : spécifiez votre clé d'API thunderforest (clé permettant d’accéder aux tuiles de la carte par défaut servies par les serveur thunderforest) dans le cas où vous utiliseriez la carte openCycleMap
ajouter les clés du fichier lib/js/translate_fr.js que vous voudriez modifier pour coller à votre association (e.g. : T_header_main : contenu du panneau supérieur de la page principale ou T_textHowToParticipate : contenu du pop up "comment participer") : cela permet de conserver vos modifications lors des mises à jours
modifier éventuellement les variables ClusterStrategyNumberOfGroupedObservations et ClusterStrategyDistance qui vont influer sur le regroupement d’observations sur les cartes publiques et d’administration (1 seul point affiché regroupant au moins ClusterStrategyNumberOfGroupedObservations observation proches de moins de  ClusterStrategyDistance pixels)
**modifier les tableaux arrayComponentsToDisableRole1Admin, arrayComponentsToDisableRole2CommunauteCommunes, arrayComponentsToDisableRole3PoleTechnique et arrayComponentsToDisableRole4Moderateur** : ces tableaux contiennent la liste des champs à désactiver pour chaque rôle défini dans la base de données (cf paragraphe m. de ce document pour avoir une vue détaillée des rôles). Les identifiants de ces champs sont listés ci-dessous avec la correspondance sur l’interface d’administration d’une observation

1. RuePOIField : Rue où se trouve l’observation, spécifiée initialement par la personne qui a enregistré l’observation
2. NumPOIField : Repère quelconque pour faciliter la localisation de l’observation, , spécifié initialement par la personne qui a enregistré l’observation
3. PrioritePOIField : Priorité donnée à l’observation par un modérateur
4. SubCategoryPOIField : catégorie liée à l’observation, , spécifiée initialement par la personne qui a enregistré l’observation
5. ObsPOIField : Observation faite par l’association
6. DescPOIField : Description faite sur l’observation, spécifiée initialement par la personne qui a enregistré l’observation
7. PropPOIField : Proposition pour résoudre l’observation, spécifiée initialement par la personne qui a enregistré l’observation
8. RespComcomPOIField : Réponse de la collectivité
9. RespPolePOIField : Réponse du pôle technique
10. CommentFinalPOIField : Commentaire final de l’association
11. CommunePOIField : Commune où se trouve l’observation
12. PolePOIField : Pôle sur lequel est située l’observation
13. StatusPOIField : Statut de l’observation donnée par la collectivité
14. latitude : latitude de la localisation de l’observation
15. longitude : longitude de la localisation de l’observation
16. ModerationPOIField : indicateur de l ‘état de modération de l’observation
17. DisplayPOIField : indicateur d’affichage de l’observation sur la carte publique
18. TraitePolePOIField : indicateutr de traitement de l’observation par le pôle
19. TransmissionPolePOIField : indicateur de transmission de l’observation de la collectivité au pôle
20. emailPOIField : e-mail de la personne qui a enregistré l’observation
21. sendMailButton : bouton d’envoi de mail à la personne qui a enregistré l’observation
![image](https://user-images.githubusercontent.com/10177830/40914702-7f062e88-67f9-11e8-9c5d-c8e8d85a5db3.png)

**Comment by tconstans** [comment]
Désolé Gérald, je viens de voir ta notif...

Je cloture
