### ISSUE TITLE
le nombre d'observations n'est pas affiché sur la page publique, mais l'est sur la page d'administration

### ISSUE THREAD

**Issue by fmalard** [2p2r/velobs_web#185]
Pour faire disparaître la référence à Toulouse Métropole, j'ai peut être modifié un fichier qui permettait l'affichage des statistiques.
![velobs08-admin-stat](https://user-images.githubusercontent.com/39265353/41806672-ecaf280e-76c2-11e8-8ee2-3827ade29669.png)
![velobs08-public-nostat](https://user-images.githubusercontent.com/39265353/41806673-ecd3f1de-76c2-11e8-8bf0-29ada42db7e5.png)

**Comment by gerald2545** [comment]
en effet, tu as dû modifier le contenu de la variable T_header_main, initialement dans translation_fr.js, et que tu as dû créé dans ton fichier key.js
Il te "suffit" de rajouter le contenu suivant dans le contenu de ta variable T_header_main pour que les stats apparaissent

<div style="float:left;" id="statsVelobs">
je vais essayer de faire en sorte que ce soit mieux identifié et plus flexible
