### ISSUE TITLE
remplacer 3101 par allô toulouse

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#19]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 13:16 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/19_

----

partout où il est question du 3101 qui ne fonctionne plus

**Comment by bikepunk** [comment]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bikepunk](https://github.com/bikepunk)**
_Saturday Dec 24, 2016 at 14:44 GMT_

----

Idéalement il faudrait mettre le bon numéro en fonction de la commune concernée. Allo toulouse concerne surtout la ville de toulouse : http://www.toulouse.fr/web/prevention-securite/allo-toulouse

**Comment by gerald2545** [comment]
bien modifié, même si je trouve la façon d'implémenter cela pas très souple
