### ISSUE TITLE
S'associer à une fiche

### ISSUE THREAD

**Issue by RoueLibre73** [2p2r/velobs_web#196]
Dans l'idée d'avoir plus de poids auprès des élus et décideurs nous souhaiterions développer la possibilité de s'associer à une remontée de terrain déjà effectuée.

**Comment by gerald2545** [comment]
Modifier l'interface de soumission d'un commentaire pour ajouter l'option 'Je soutiens cette demande'
Donner la possibilité aux personnes ayant ajouté un commentaire ou soutenu une demande de recevoir les informations sur la mise à jour de l'observation : ajouter une chckbox 'je veux recevoir les mises à jour de cette fiche"

**Comment by gerald2545** [comment]
![image](https://user-images.githubusercontent.com/10177830/52002018-2801b780-24c1-11e9-8452-c039d9b3a99b.png)
Que penses-tu des premiers écrans? ça te convient?
Je regarde pour enregistrer tout ça en base de données et afficher l'info sur les interfaces publique et privées

**Comment by gerald2545** [comment]
Message après avoir cliqué : 
![image](https://user-images.githubusercontent.com/10177830/52036867-0db1f300-252e-11e9-96c3-a80631c319e7.png)

affichage de l'info sur interface publique : 
![image](https://user-images.githubusercontent.com/10177830/52036991-3afea100-252e-11e9-9492-cddf79342908.png)
affichage de l'info sur l'interface d'admin : 
![image](https://user-images.githubusercontent.com/10177830/52037081-5e295080-252e-11e9-8044-046a45b32904.png)

**Comment by RoueLibre73** [comment]
Super, ça semble bien. Je te redis dès que j'ai fait a MAJ.

**Comment by gerald2545** [comment]
faire en sorte de mettre les personnes qui ont voté et qui ont choisi de recevoir les mails, d'être dans la liste des destinataires des mails lors des mises à jour
