### ISSUE TITLE
Centraliser les adresses mails From, Reply-To et To dans le fichier de config

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#2]
<a href="https://github.com/gerald2545"><img src="https://avatars.githubusercontent.com/u/10177830?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gerald2545](https://github.com/gerald2545)**
_Wednesday May 11, 2016 at 18:55 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/2_

----

**Comment by gerald2545** [comment]
tout est dans le fichier lib/php/key.php
