### ISSUE TITLE
faire un config file pour centraliser toutes les valeurs à changer pour adapter VélObs à une autre ville

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#20]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 13:17 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/20_

----

**Comment by gerald2545** [comment]
le fichier lib/php/key.php remplit ce rôle
On peut fermer cette issue?
