### ISSUE TITLE
Remplissage automatique des champs adresse

### ISSUE THREAD

**Issue by RoueLibre73** [2p2r/velobs_web#200]
Serait-il possible que lorsqu'on clique sur la carte pour positionner la fiche, les champs adresse se remplissent automatiquement?

**Comment by gerald2545** [comment]
c'est une demande qui revient assez régulièrement, peut-être pour la V2 (pas planifiée)

**Comment by gerald2545** [comment]
Updating map.js->createFeatureAdd()
having lon and lat of the feature, calling lib/php/public.getAdresse.php with ajax
return the name of the street and the number, according to  https://adresse.data.gouv.fr/api

**Comment by gerald2545** [comment]
- [ ] add the possibility to deactivate this functionality in key.js.template

**Comment by gerald2545** [comment]
added
//Allow to get the street of the observation given by the user while submitting a new observation
var activateReverseGeocoding = true;
