### ISSUE TITLE
Impossible de faire une observation avec chrome

### ISSUE THREAD

**Issue by tconstans** [2p2r/velobs_web#206]
Hello,
Un de nos utilisateurs signale l'impossibilité de faire une obs avec chrome. Pas de soucis avec firefox...

À votre dispo pour plus d'info

**Comment by gerald2545** [comment]
testé à l'instant avec Chrome Version 73.0.3683.86 (Build officiel) (64 bits) sur PC windows 7 64 bits > pas de problème.
Merci de demander à votre utilisateur de compléter cette fiche avec le maximum de détails pour que je puisse reproduire le cas échéant.
