### ISSUE TITLE
supprimer le champ longitude de l'interface de modération des poles asso

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#21]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 14:18 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/21_

----

le bouton modérer suffit ;)

**Comment by gerald2545** [comment]
cette colonne n'est plus affichée sur les comptres des pole, mais encore sur les comptes de modérateurs, à supprimer
