### ISSUE TITLE
afficher les zones géographiques sur la carte publique

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#23]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Thursday Oct 27, 2016 at 06:15 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/23_

----

poles TM, SICOVAL et Muretain

**Comment by gerald2545** [comment]
ajout case à cocher "limites" permettant d'afficher les limites des communes definies dans velobs. ajout aussi du layerswitcher à droite

**Comment by gerald2545** [comment]
boutons ajoutés sur l'interface publique pour afficher contours des poles et/ou des communes : 
![image](https://user-images.githubusercontent.com/10177830/31742487-0a1f08ec-b458-11e7-8771-1443830d4824.png)
