### ISSUE TITLE
Commentaire de l'association

### ISSUE THREAD

**Issue by RoueLibre73** [2p2r/velobs_web#235]
Lors de la modération des fiches, le dernier commentaire inscrit dans la fenêtre modération/commentaire final est conservé lors des prochaines modération, ce qui peut conduire à des erreurs. Paramétrer ce champ pour que la valeur par défaut lors de la  première modération soit vide;

**Comment by gerald2545** [comment]
Est-ce que tu pourras retester après avoir mis à jour velobs?  
Je n'arrive pas à reproduire sur ma version (1.7.0)  

merci d'avance

**Comment by gerald2545** [comment]
pas de retour, on ferme
