### ISSUE TITLE
Remplacer "POI" par Observation

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#24]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Thursday Oct 27, 2016 at 07:57 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/24_

----

au moins dans les mails envoyés
Point Of Interest n'est explicite que pour les habitués de la cartographie :/

**Comment by gerald2545** [comment]
valider que toutes les occurences de POI sont bien remplacées avant cloture

**Comment by gerald2545** [comment]
nouveaux remplacements effectués dans le fichiers de langue javascript
