### ISSUE TITLE
ajouter des champs dans les mails pour le changement de statut

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#25]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bikepunk](https://github.com/bikepunk)**
_Sunday Nov 13, 2016 at 19:17 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/25_

----

Dans les mails envoyés pour les changements de statut type :
"[Association 2 pieds 2 roues]Changement de statut de l'enregistrement n°"
il faudrait ajouter au moins le lien vers l'observation.
et  les champs utiles à l'identification de l'observation pour ne pas avoir à ouvrir vélobs

**Comment by gerald2545** [comment]
ajout des détails + lien vers l'interface d'admin  + lien publique
