### ISSUE TITLE
Lien mort pour image absente

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#256]
Dans certains contextes, un lien mort est affiché quand il n'y a pas d'image.
Exemple actuel : https://velobs.2p2r.org/admin.php?id=4209

![image](https://user-images.githubusercontent.com/41120158/97152757-aa400e00-1771-11eb-8bfb-d8c01d704537.png)

Merci !

**Comment by gerald2545** [comment]
en effet, je l'ai constaté aussi sur une autre observation, mais n'ai pas eu le temps d'investiguer encore. Il ne semble pas qu'il y ait de pertes de fichiers vu que ça fonctionne pour observations, mais à approfondir asap
