### ISSUE TITLE
Renommer "Jalonnement" en "Signalisation"

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#258]
Actuellement il y a une catégorie d'observations appelée "Jalonnement". Je propose de la renommer en "Signalisation" car le terme me paraît plus approprié et parce que c'est à cela qu'elle sert finalement.
Merci

**Comment by tszym** [comment]
Le jalonnement et la signalisation sont deux concepts différents. Le jalonnement est l'indication d'itinéraire à suivre pour aller dans une direction approximative ou atteindre une destination précise. La signalisation englobe bien plus de choses, comme des contraintes réglementaires.

Il ne semble pas nécessaire de modifier la sous-catégorie Jalonnement existant par défaut, puisqu'il s'agit d'un concept pouvant être légitime, et que l'administrateur a la possibilité de modifier les sous-catégories existantes ou en ajouter de nouvelles en fonction de ses besoins.

**Comment by sebastienaubry** [comment]
Bonsoir,
Je suis d'accord avec les définitions, je fais juste le constat que sur VelObs Toulouse cette catégorie est utilisé pour des dizaines de problèmes qui relèvent de la signalisation, et non du jalonnement. Or, il n'y a pas de catégorie dédiée à la signalisation. D'où ma proposition de "recycler" cette catégorie en "Signalisation" pour mieux couvrir les observations existantes qui en relèvent pour la plupart.

**Comment by tszym** [comment]
Je ne sais pas à quel point les tickets ici peuvent être spécifiques à l'instance de Toulouse. J'ai répondu du point de vue du logiciel en lui-même, pas d'une installation spécifique.

**Comment by sebastienaubry** [comment]
Une autre solution, qui me conviendrait aussi bien, serait de créer une
catégorie Signalisation. C'est sans doute plus générique.

Le mar. 25 mai 2021 à 22:05, Thomas Szymanski ***@***.***> a
écrit :

**Comment by gerald2545** [comment]
Remplacement Jalonnement par Signalisation, plus générique et correspondant mieux aux observations trouvées dans velobs
