### ISSUE TITLE
Fusion d'observations

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#262]
En cas de doublon, il serait intéressant de permettre la fusion de 2 observations A et B.
Soit A la plus ancienne. Il s'agirait :
- si A n'a pas de photo et B en a une, de la reprendre
- de créer un commentaire sur A avec l'e-mail de l'observateur de B (en mode silencieux) du type "{B.observation}.\nProposition : {B.proposition}" et, si A avait déjà une photo (étape précédente), la photo de B
- de copier dans A tous les commentaires de B
- d'ajouter un vote à A avec l'e-mail de l'observateur de B (en mode silencieux mais en activant les notifications ultérieures)
- de copier sur A tous les votes de B
- d'ajouter un commentaire à B : "Observation fusionnée avec #{A.id} : https://velobs.2p2r.org/index.php?id={A.id}" et de marquer B comme "Doublon".

**Comment by gerald2545** [comment]
oui, bonne idée
je regarde ça.

genre quand sur une observation on positionne la priorité à Doublon > alors on affiche une fenêtre demandant l'id de l'observation qu'elle doublonne pour faire ce que tu proposes

**Comment by sebastienaubry** [comment]
Ou plus simplement, un bouton "Fusionner avec..." sur la page d'édition de
l'observation.



Le dim. 22 nov. 2020 à 11:05, gerald2545 <notifications@github.com> a
écrit :

**Comment by gerald2545** [comment]
![image](https://user-images.githubusercontent.com/10177830/104824914-8d8a1280-5856-11eb-9de3-b207b9c23649.png)

**Comment by gerald2545** [comment]
Test

- [ ] au moins 1 id non spécifié
- [ ] au moins 1 id d'observation n'existe pas
- [ ] les 2 id sont identiques
- [ ] ordre de l'id dans les champs croissant ou décroissant

**Comment by sebastienaubry** [comment]
Bonjour,
Dans le commentaire généré, la proposition initiale pourrait être reprise : elle appuie le constat et le complète parfois.
Merci
