### ISSUE TITLE
Taille des commentaires

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#266]
La limite est de 500 caracères pour le champ des commentaires. Il faudrait l'augmenter.

Par exemple sur :
https://velobs.2p2r.org/admin.php?id=2953 en mode "modération de commentaires"

Je cherche à mettre le texte suivant à la place du 2e commentaire :
"Les piétons sont censés traverser au passage piéton pour prendre la rampe qui descend en zig-zag vers le B612 mais quasiment aucun le fait. Résultat, dans la descente/montée près du Blok, il y a parfois un groupe de piétons qui descend, un cycliste qui descend vite et un autre qui monte (avec difficulté car c'est raide) et se retrouve face aux piétons. C'est dangereux. Il faudrait prolonger le trottoir jusqu'en bas. Il y a à nouveau de gros travaux à cet endroit là, mais pour faire quoi ? Mystère."

mais cela ne passe pas, la modification ne se fait pas.
Si j'enlève "Mystère" ça passe :

"Les piétons sont censés traverser au passage piéton pour prendre la rampe qui descend en zig-zag vers le B612 mais quasiment aucun le fait. Résultat, dans la descente/montée près du Blok, il y a parfois un groupe de piétons qui descend, un cycliste qui descend vite et un autre qui monte (avec difficulté car c'est raide) et se retrouve face aux piétons. C'est dangereux. Il faudrait prolonger le trottoir jusqu'en bas. Il y a à nouveau de gros travaux à cet endroit là, mais pour faire quoi ?"

J'en profite pour demander à nouveau des champs plus grands pour voir tout le commentaire sans scroller, et autoriser les retours à la ligne (#261).

On dirait que la limite à la création n'est pas la même qu'à l'édition : parfois on ne peut pas simplement enlever 1 ou 2 caractères, on est obligé d'en enlever beaucoup.

Merci

**Comment by sebastienaubry** [comment]
Un exemple : ce commentaire déposé sur https://velobs.2p2r.org/admin.php?id=2942 fait 776 caractères.
Mais à l'édition on doit être limité à 500, donc il est impossible de le modifier.

"Ce passage sous le pont est extrêmement dangereux. Aux heures de pointe, on se retrouve  piétons et vélos à se croiser  dans les 2 sen, en équilibre sur ce trottoir étroit, entre le mur d'un coté et les voitures et camions de l'autre! C'est dingue que des ingénieurs aient pu faire un tel choix d'aménagement! Je suis tombé il y a 2 ans en tentant de remonter sur le trottoir, effrayé par une voiture qui a surgi derriere moi, et j'ai failli passer sous la voiture. Depuis je prends toujours la voie des voitures. Quelques automobilistes se mettent en colère, pas tous jes jours heureusement. Il me semble que la meilleure option serait de sacrifier la voie de bus sous le pont. De toute façon les bus n'ont qu'une seule voie qu'ils se partagent deja sous le pont. Alors pour eux, ça ne devrait pas changer grand chose puiqu'ils n'ont déjà pas une voie complète pour eux dans les 2 sens."

**Comment by gerald2545** [comment]
limite passée à 3000
