### ISSUE TITLE
Zoom sur les photos des commentaires

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#267]
Actuellement, il est possible de zoomer sur la photo principale d'une observation en cliquant dessus, mais pas sur celles des commentaires. Ce serait bien d'harmoniser la fonction d'affichage, avec un zoom possible dans les deux cas.
Exemple : https://velobs.2p2r.org/index.php?id=4216
Merci

**Comment by gerald2545** [comment]
fait
