### ISSUE TITLE
Exports au format géographique

### ISSUE THREAD

**Issue by ptaluy** [2p2r/velobs_web#270]
Bonjour,

Avec le développement de umap, il peut être extrêmement utile d'exporter les points saisis dans velobs_web sous un format géographique (type geojson ou kml) qui sont balisés comme des fichiers .xml.

Eventuellement, l'export en .csv pourrait intégrer deux colonnes contenant les coordonnées géographiques (mais c'est nettement moins pratique pour la valorisation sous umap).

Un exemple de code est proposé sur cette page : 
https://stackoverflow.com/questions/52373462/save-php-output-as-a-geojson-file

Cette nouvelle possibilité d'export pourrait faciliter grandement la valorisation des fiches velobs (via umap) et nos échanges avec la collectivité (on serait en mesure de produire une synthèse sous SIG qu'ils pourraient réimporter facilement).

Merci d'avance pour le suivi.

**Comment by gerald2545** [comment]
Bonjour,
toujours intéressé par cette demande?
avec mes excuses pour le délai

**Comment by gerald2545** [comment]
a noter, l'export des observations via l'interface publique (https://github.com/2p2r/velobs_web/blob/master/documentation_utilisateurs.md#g%C3%A9n%C3%A9ration-dun-fichier-texte-csv) vous permettra de faire des imports dans umap.
Il suffit pour le moment de remplacer manuellement(si besoin, je peux modifier ça une bonne fois pour toutes) : 
Latitude par lat
Longitude par lon
les ; par des ,

ça donne un truc du style : https://umap.openstreetmap.fr/fr/map/estimation-besoin-en-stationnement-velo-inrae_605486#13/43.5766/1.5216

**Comment by ptaluy** [comment]
Bonjour, clairement oui, toujours intéressé, l'idée est de les exporter sur umap notamment pour des valorisations tierces. Le format d'export peut être n'importe quel format SIG, je sais tout convertir.

Bonne journée !
     Le dimanche 16 octobre 2022, 23:09:45 UTC+2, gerald2545 ***@***.***> a écrit :  
 
 


Bonjour,
toujours intéressé par cette demande?
avec mes excuses pour le délai

**Comment by ptaluy** [comment]
Pas mal du tout, je vais regarder ça !
Merci !!!
     Le dimanche 16 octobre 2022, 23:50:18 UTC+2, gerald2545 ***@***.***> a écrit :  
 
 


a noter, l'export des observations via l'interface publique (https://github.com/2p2r/velobs_web/blob/master/documentation_utilisateurs.md#g%C3%A9n%C3%A9ration-dun-fichier-texte-csv) vous permettra de faire des imports dans umap.
Il suffit pour le moment de remplacer manuellement(si besoin, je peux modifier ça une bonne fois pour toutes) :
Latitude par lat
Longitude par lon
les ; par des ,

ça donne un truc du style : https://umap.openstreetmap.fr/fr/map/estimation-besoin-en-stationnement-velo-inrae_605486#13/43.5766/1.5216
