### ISSUE TITLE
La réponse du Pôle n'est pas visible publiquement

### ISSUE THREAD

**Issue by marcellin31** [2p2r/velobs_web#271]
Bonjour

Point discuté avec Gérald Salin et Marcellin DAGICOUR (email du 21/04/2021)

Pour fonsorbes, il a été décidé de donner le rôle de "Pole" à l'élu de la commune pour commenter les points Velobs. Mais **le problème c'est que ces commentaires di Pôle ne sont pas visibles par tous et notamment le grand public**.

Voici un exemple https://velobs.2p2r.org/index.php?id=4053

Voici la vue avec le role "Collectivité":
![Capture d’écran 2021-04-21 200326 vu par la collectivite](https://user-images.githubusercontent.com/82969199/115600740-4c821e00-a2dd-11eb-8547-e23500fca4a2.jpg)

Voici la vue sans accès particulier, il manque la réponse du pôle:
![Velobs reponse pole pas visible](https://user-images.githubusercontent.com/82969199/115600746-4d1ab480-a2dd-11eb-8b39-2264d1b78d95.jpg)

Donc le développement consiste à rendre ce champs visible par tous une fois le sujet "Traité par le pole".

Merci

MArcellin

**Comment by gerald2545** [comment]
la réponse du pôle sera maintenant visible
