### ISSUE TITLE
Déplacement des observations impossible - Problème serveur de tuiles

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#277]
Apparemment il va falloir changer le serveur de tuiles utilisé pour l'édition des observations. De toute façon il me paraissait obsolète par rapport à la carte principale.
Cela rend le déplacement des observations impossible.

![image](https://user-images.githubusercontent.com/41120158/154973840-4ca98349-1459-4812-b956-fc07ad8792e6.png)

Merci

**Comment by gerald2545** [comment]
semble OK après remplacement de 
var adminMapForPoi = new OpenLayers.Layer.OSM("OpenStreetMap Hikebike", "http://toolserver.org/tiles/hikebike/${z}/${x}/${y}.png");
par 
var adminMapForPoi = new OpenLayers.Layer.OSM("OSM Cycle Map", 'https://tile.thunderforest.com/cycle/${z}/${x}/${y}.png?apikey='+ TF_key);
