### ISSUE TITLE
URL d'administration inopérantes

### ISSUE THREAD

**Issue by sebastienaubry** [2p2r/velobs_web#278]
Quand on clique sur l'URL d'admin https://velobs.2p2r.org/admin.php?id=2740 ça n'ouvre pas la fenêtre d'administration de l'observation. Il faut manuellement taper "2740" dans la case en bas à gauche pour l'ouvrir.

**Comment by gerald2545** [comment]
désolé, je n'arrive pas à reproduire, quand je clique sur le lien, j'ai bien la fenêtre d'admin de l'observation qui s'ouvre.

Peux-tu me donner plus d'infos pour reproduire (es-tu déjà connecté ou non à l'interface d'admin, as-tu déjà une autre fenêtre d'administration ouverte)..

merci d'avance

**Comment by sebastienaubry** [comment]
Je viens de le reproduire à l'instant avec un navigateur que je viens
d'ouvrir (Firefox). Je n'étais pas connecté. Je clique sur le lien
https://velobs.2p2r.org/admin.php?id=2740. Je m'identifie. Ça n'ouvre pas
l'observation en question. Je recharge la page, idem, ça n'ouvre pas
l'observation.
Même comportement sous Chrome.

**Comment by LucN31** [comment]
Bonsoir,
Idem pour moi avec Firefox ESR 91.8.0esr (64 bits) et avec Brave Version 1.38.109 (Chromium: 101.0.4951.41 (Build officiel) (64 bits)) sous Linux Debian.
Que je sois connecté ou pas, même comportement, il faut entrer le numéro d'observation pour que la fenêtre admin apparaisse. Ce problème n'est pas présent en consultation (sans admin.php dans le lien).

**Comment by gerald2545** [comment]
désolé pour le délai. OK , je reproduis avec un compte de modérateur, mais pas un rôle d'admin....ça va être vite corrigé

**Comment by gerald2545** [comment]
corrigé, la prod est patchée
