### ISSUE TITLE
migrer de ext/mysql vers PDO_MySQL

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#28]
dans la doc de PHP, https://secure.php.net/manual/en/mysqlinfo.api.choosing.php

il est indiqué qu'il vaut mieux utiliser ext/mysqli ou PDO_MySQL plutot que ext/mysql qui est déprécié.

PDO a l'avantage d'être compatible avec 12 drivers https://secure.php.net/manual/en/pdo.drivers.php
(il permet donc, avec le même code, de faire des requetes dans MySQL ou dans PostgreSQL ou autre)

**Comment by gerald2545** [comment]
V1.1 intègre  ext/mysqli, merci Lydie
