### ISSUE TITLE
Export - Ajouter une colonne "Date de dernière modification" dans les exports csv des signalements

### ISSUE THREAD

**Issue by jpborges78** [2p2r/velobs_web#284]
Il serait intéressant d'ajouter une colonne "Date de dernière modification" dans les exports des listes de signalements.

Cela permettrait de vérifier rapidement qu'un signalement a été mis à jour ou non avant d'envoyer une liste aux élus de la commune avec lesquels on correspond.

Et si, en plus, on peut avoir le nom et l'email de la personne qui a généré cette dernière modification, ce serait parfait.
Merci

**Comment by gerald2545** [comment]
sera effectif lors de la prochaine mise en production
