### ISSUE TITLE
Bug dans la visualisation des observations en liste dans Velobs

### ISSUE THREAD

**Issue by LucN31-2** [2p2r/velobs_web#285]
**Description du bug**
Certaines observations visibles dans la représentation "*La carte*" et présentes dans l'extraction au format CSV ne sont pas visibles depuis l'onglet "*Observations*".

**Pour reproduire**
1.  Recherchez l'observation n° 4376 (ou n° 4377) dans l'interface "*La carte*", elle apparaît normalement.
1.  Basculez sur l'onglet "*Observations*" et triez suivant le numéro d'observation. 
1.  **Toutes les lignes ne sont pas affichées,**
1.  Exportez les observation en CSV,
1.  Toutes les observations sont présentes.

**Fonctionnement attendu**
Toutes les observations devraient être affichées dans les différents cas.

**Copies d'écran**

1.  Vue partielle dans Velobs : 
![Vision dans Velobs](https://user-images.githubusercontent.com/53767760/230162368-04f18bb8-0972-417d-9423-1973da99eddb.png)

2.  Vue de l'extraction au format CSV : 
![Extraction CSV](https://user-images.githubusercontent.com/53767760/230162372-4972ff5d-9639-44b2-b88a-ee0fd53bf9d7.png)

**Velobs instance**
 - [https://velobs.2p2r.org/admin.php](https://velobs.2p2r.org/admin.php)

**Ordinateur**
 -  OS : Debian 11
 -  Browser : Brave 
 -  Version : 1.49.132 Chromium: 111.0.5563.147 (Build officiel) (64 bits)

**Comment by gerald2545** [comment]
salut Luc,
très juste, le problème n'arrive que pour les modérateurs, reliquat de l'époque où ceux-ci ne pouvaient voir que les observations correspondant à la zone où il sont déclarés comme modérateur. Je corrige

**Comment by gerald2545** [comment]
c'est corrigé en direct sur le serveur, en attendant la mise en prod de la nouvelle version
