### ISSUE TITLE
créer une fonction d'envoi de mail

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#3]
<a href="https://github.com/gerald2545"><img src="https://avatars.githubusercontent.com/u/10177830?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gerald2545](https://github.com/gerald2545)**
_Wednesday May 11, 2016 at 18:59 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/3_

----

des mails sont envoyés à prtir de plusieurs fichiers source. Centraliser une fonction d'envoi de mail pour faciliter toute évolution future de la config des mails

**Comment by gerald2545** [comment]
implémenté depuis janvier
