### ISSUE TITLE
Liste déroulante "type d'observation" vide

### ISSUE THREAD

**Issue by tconstans** [2p2r/velobs_web#35]
Hello,

Je teste l'appli pour La Ville à Vélo Lyon (https://lavilleavelo.org)

Je l'ai installé sur une machine de test, ai modifié les données pour centrer la carte sur Lyon.

Par contre lors de la création d'une "nouvelle observation", la liste déroulante pour le type est déspéremment vide. J'imagine que son contenu vient d'une table, mais impossible de savoir laquelle.

Une idée ?

**Comment by tconstans** [comment]
Bon je me réponds à moi même, il s'agit de la table *subcategory*

**Comment by gerald2545** [comment]
Bonjour tconstants,
je viens seulement de voir votre issue...désolé
qu'ont donné vos test sur Lyon?
