### ISSUE TITLE
enregistrer les mails des contributeurs pour les nouvelles photos / commentaires

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#4]
<a href="https://github.com/gerald2545"><img src="https://avatars.githubusercontent.com/u/10177830?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gerald2545](https://github.com/gerald2545)**
_Sunday May 15, 2016 at 20:07 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/4_

----

les applis iOS et android envoient l'adresse mail du contributeur.
Mettre à jour la base de données et modifier la partie serveur pour prendre en compte cette information.
Si le mail correspond à un modérateur, afficher directement le nouveau commentaire ou la nouvelle photo (comme pour la création d'une nouvelle fiche velobs).
Extrait du mail de Fabien : "_Testé sur mon serveur , j'envoie le paramètre mail avec comme valeur le mail que l'utilisateur renseigne au début.
Cela n'affecte pas le fonctionnement du serveur qui pour l'instant ne prend pas en compte ce paramètre_ "

**Comment by gerald2545** [comment]
faire en sorte de pouvoir spécifier 1 photo et 1 commentaire en même temps, ou un seul des 2

**Comment by gerald2545** [comment]
il faut merger les tables commentaires et photos, modifier la table commentaires pour qu'elle référence l'id_poi (pas besoin de table intermédiaire poi_commentaires.....) et supprimer les tables poi_photos, photos et poi_commentaires : 

- ajouter colonne url_photo dans la table commentaires
- ajouter colonne mail_commentaires dans la table commentaires
- ajouter colonne poi_id_poi dans la table commentaires
- mettre à jour les enregistrements existants dans la table commentaires en positionnant poi_id_poi en se basant sur le contenu de la table poi_commentaires
- créer les enregistrements de la table photos dans la table commentaires en ne renseignant que display_commentaires, url_photo et poi_id_poi

Mettre à jour tous les fichiers php et interfaces utilisant toutes ces tables pour ne plus utiliser que la table commentaires (code source à identifier) 

créer un script d'upgrade pour la base de données

**Comment by gerald2545** [comment]
ALTER TABLE commentaires ADD url_photo varchar(500) default null;

ALTER TABLE commentaires ADD mail_commentaires varchar(100) default null;
ALTER TABLE commentaires ADD poi_id_poi int(11) not null;
//mettre à jour commentaires.poi_id_poi à partir de poi_commentaires puis
ALTER TABLE commentaires ADD CONSTRAINT `commentaires_ibfk_1` FOREIGN KEY (`poi_id_poi`) REFERENCES `poi` (`id_poi`);

**Comment by gerald2545** [comment]
appli mobile android V1 (https://framagit.org/2P2R/velobs-android) prête pour cette fonctionnalité
