### ISSUE TITLE
faire 1 seul et même traitement pour la création d'une observation avec photo

### ISSUE THREAD

**Issue by gerald2545** [2p2r/velobs_web#59]
A l'heure actuelle, l'observation est créée via lib/php/admin/adminfunction.php >createPublicPoi() et la photo associé chargées avec lib/php/public/uploadPhoto.php
Ce qui fait que : 

- si l'observation est bien enregistrée mais que la photo ne passe pas, on aura une observation sans photo dans la BDD

- le mail envoyé à la création de l'observation dit qu'il n'y a pas de photo associée, alors que ce n'est pas vrai

tout combiner dans createPublicPoi pour avoir un minimum d'atomicité

**Comment by gerald2545** [comment]
prendre modèle sur map.js > createTheComment c$oté client et adminfunction.php > createPublicComment() côté serveur

**Comment by plateforme-genomique-toulouse** [comment]
modification de map.js>createPublicPOI pour envoyer formulaire en 1 fois au serveur 
modification de adminfunction.php > createPublicPoi() pour gérer photo + données de formulaire de façon atomique

**Comment by gerald2545** [comment]
suppression des fichiers lib/php/admin/uploadPhotoSupp.php et uploadPhotoSuppPublic.php, lib/php/public/uploadPhoto.php, lib/php/mobile/uploadPhoto.php
