### ISSUE TITLE
mise à jour impossible de la priorité

### ISSUE THREAD

**Issue by bikepunk** [2p2r/velobs_web#6]
<a href="https://github.com/gerald2545"><img src="https://avatars.githubusercontent.com/u/10177830?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gerald2545](https://github.com/gerald2545)**
_Friday Sep 23, 2016 at 05:06 GMT_
_Originally opened as https://github.com/2p2r/velobs/issues/6_

----

Je voulais passer des fiches velobs à DONE, mais les modifs n'ont pas été prises en compte
Quand je choisis DONE dans la liste déroulante, le champs passe à la la valeur 6, mais si je navigue ensuite entre les pages du tableau et que je reviens sur ma fiche, celle-ci est à la même priorité qu'auparavant

**Comment by bikepunk** [comment]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 13:34 GMT_

----

j'ai le même problème aujourd'hui sur l'observation 2574, j'essaye de comprendre

**Comment by bikepunk** [comment]
<a href="https://github.com/bikepunk"><img src="https://avatars.githubusercontent.com/u/14958221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bikepunk](https://github.com/bikepunk)**
_Wednesday Oct 26, 2016 at 13:49 GMT_

----

le changement de priorité ne fonctionne pas dans le tableau, mais dans l'interface popup ( http://velobs.2p2r.org/admin.php?id=2574 ), je peux effectivement changer la priorité !

 à voir comment fixer ça

**Comment by gerald2545** [comment]
Dans lib/php/admin/adminfunction.php, fonction updatePoi, le sql pour mettre à jour le POI n'est jamais exécuté, contrairement aux fonctions updatePoiComcomCarto, updatePoiPoleTechCarto....

**Comment by gerald2545** [comment]
oups, il est bien appelé juste avant la fin de la fonction, mais la variable de mise à jour du POI ($sql) est écrasée entre temps  ...
revoir ces fonctions de mise à jour de POI pour mutualiser le code et le clarifier avec des commentaires

**Comment by gerald2545** [comment]
Corrigé et passé en prod
