### ISSUE TITLE
Erreur lors d'import de fichiers sql dans base de données

### ISSUE THREAD

**Issue by axelos** [2p2r/velobs_web#74]
Salut les copains,

Je rencontre un petit souci lorsque j’essaie de téléverser les fichiers sql dans une base de données mariadb (un fork de mysql) qui est proposé par défaut sur Debian 9.

Avec le fichier 17_poi_commentaires.sql j'ai comme réponse : 
`ERROR 1005 (HY000) at line 42: Can't create table `velobs_db`.`#sql-318_43a` (errno: 150 "Foreign key constraint is incorrectly formed")`

18_poi_photos.sql
`ERROR 1005 (HY000) at line 42: Can't create table `velobs_db`.`#sql-318_45b` (errno: 150 "Foreign key constraint is incorrectly formed")`

19_poi.sql
`ERROR 1005 (HY000) at line 77: Can't create table `velobs_db`.`#sql-318_46a` (errno: 150 "Foreign key constraint is incorrectly formed")`

06_translation.sql
`ERROR 1005 (HY000) at line 96: Can't create table `velobs_db`.`#sql-3972_29` (errno: 150 "Foreign key constraint is incorrectly formed")`

Et dans les détails ces erreurs renvois sur ce message :
->  Percona-XtraDB, Supports transactions, row-level locking, foreign keys and encryption for tables 

J'ai de bonnes bases en sys admin GNU/Linux, pour le reste notamment la gestion des bases de données c'est pas mon fort.

Voilà, Axel pour EDEN Nancy.

**Comment by gerald2545** [comment]
Bonjour Axel,
Je confirme ce que tu décris, j'ai reproduis ce matin sur un serveur "5.5.47-MariaDB - MariaDB Server". La table est bien créée, mais la définition des clés étrangères n'est pas appliquée.
Quelle est ta version de mariadb?
tu utilises phpMyAdmin pour faire l'import?

A noter, @florent-morel a fait un fork pour faciliter la création du SQL pour une première install de velobs : 
https://github.com/florent-morel/velobs_web/tree/generic_install (cf resources/sql)
je n'ai pas encore eu le temps de m'y plonger, mais je pense qu'en fin de semaine je pourrai tester

**Comment by axelos** [comment]
Merci pour la réactivité (réponse + tests)

> Je confirme ce que tu décris, j'ai reproduis ce matin sur un serveur "5.5.47-MariaDB - MariaDB Server". La table est bien créée, mais la définition des clés étrangères n'est pas appliquée.
> Quelle est ta version de mariadb?
> tu utilises phpMyAdmin pour faire l'import?

Pour répondre aux questions, la version de Mariadb utilisée est la 10.1 (la version du paquet 10.1.26-0+deb9u1).
J'ai trouvé bizarre la comparaison de nos versions, mais en fait ça passe de la version 5 à 10 directement …
https://downloads.mariadb.org/mariadb/+releases/

Ensuite, j'ai bien utilisé l'interface phpmyadmin, mais aussi avec ce type de commande
`root@web:/home/web# mysql < /home/velobs/resources/sql/18_poi_photos.sql velobs_db -u velobs -p`
Ça retourne les mêmes erreurs.

> A noter, @florent-morel a fait un fork pour faciliter la création du SQL pour une première install de velobs :
> https://github.com/florent-morel/velobs_web/tree/generic_install (cf resources/sql)
> je n'ai pas encore eu le temps de m'y plonger, mais je pense qu'en fin de semaine je pourrai tester puis merger si OK

Merci pour l'info, je vais attendre alors  :)

**Comment by gerald2545** [comment]
vu sur la branche de Florent et ça devrait fonctionner, importe : 
- language.sql avant translation.sql
- poi.sql avant poi_commentaires.sql

par contre, tu auras les données de Toulouse en terme de communes et poles techniques....
Peux-tu m'envoyer ton mail STP de façon à ce que je t'envoie une doc (à finaliser) qui explique comment importer les limites géographiques des communes/poles) dans velobs

A+

**Comment by axelos** [comment]
> par contre, tu auras les données de Toulouse en terme de communes et poles techniques....

Mais c'est aussi le cas sur la branche principale non ?

> Peux-tu m'envoyer ton mail STP de façon à ce que je t'envoie une doc (à finaliser) qui explique comment importer les limites géographiques des communes/poles) dans velobs

Ok merci c'est sympa, c’était ma question suivante :) axelos@broman.fr

En revanche je serais indisponible quelques jours, donc le retour attendra un peu … À bientôt.

**Comment by gerald2545** [comment]
simplification en cours : 1 seul fichier SQL contenant l'ensembles des scripts SQL initiaux (simplifiés : suppression des insertions des enregistrements concernant Toulouse en terme de communes, poles, quartiers) + ajout des catégories et subcategories + création d'un compte admin de base + réorganisation des import des tables pour ne pas avoir le problème de clés étrangères non existantes

**Comment by axelos** [comment]
Bonjour,
Ce problème n’est plus, le nouveau fichier unique passe sans erreur.

Merci !
