### ISSUE TITLE
Echec à l'installation des scripts SQL

### ISSUE THREAD

**Issue by PatriceLepissier** [2p2r/velobs_web#79]
Bonjour,

J'essaie d'installer l'application Velobs, sur un serveur hébergé chez Online (hébergement mutualisé), pour une version d'essai dans le cadre de Brive Ville Cyclable.
Lors de l'importation des scripts SQL (téléchargés depuis le dossier velobs_web-master.zip), j'ai une erreur sur le script 04_pole.sql : "Erreur 500 : internal server error" ... et MySQL has gone away. (Cf [image écran ici](http://www.lepissier.org/velobs/basesperso/Erreur-Import-04.png))
J'ai trouvé le fichier velobs_web-generic-install.zip (je ne peux pas lancer le fichier .sh sur le serveur mutualisé), le même fichier pose le même problème.
NB : lors d'une première installation j'avais également eu un problème sur la création des clés étrangères pour les 3 dernières tables.
Est-ce un problème avec la version MySql de Online, ou autre ?
Merci pour votre aide.

**Comment by gerald2545** [comment]
Bonjour Patrice;
désolé, pas vu ton issue avant, je ne sais pas comment être averti par mail lorsqu'il y a de nouvelles issues..ll va falloir que je me replonge dans la config de github..
Sinon pour ton problème, il se peut que la version mysql soit en cause. Peux-tu me dire la version de mysql STP?
Est-ce que la table pole a bien été créée?
si oui, fait un export de cette table et lie le à cette issue

A+

Gérald

**Comment by PatriceLepissier** [comment]
Bonjour,
La version Mysql : 5.5.34, PHP : 5.4.9-4Ubuntu2.4
J'ai créé la table pole sans l'insertion des données, puis j'ai tenté d'insérer les 2 premières lignes -> plantage.
J'ai fait la même manip sur un serveur Mysql que je viens d'installer sur mon PC, à l'insertion des 2 premières lignes de données j'ai l'erreur : "Cannot get object from data you send to the GEOMETRY field" ... Le problème doit venir du contenu du champ GEOMETRY (NB : qui s'est bien enregistré pour la table des communes).
Les lignes à insérer m'intéressent peu puisque je ne veux pas tester sur Toulouse, mais sur Brive.
Ma question : où est-ce que je peux trouver la définition du polygone des limites de communes et de la ComCom (Agglo de Brive) ? J'ai l'impression que ce serait disponible dans OSM, mais je n'y connais rien en système de cartographie.
Merci pour les infos.
Patrice

**Comment by gerald2545** [comment]
Bonjour,
nous sommes en train de travailler pour faciliter les nouvelles installations, notamment quand on n'a pas de compétences en SIG (comme moi ;)).
On trouve les contours de communes en opendata avec OSM. Voici la procédure mise en place pour l'extraction des limites des communes : 

- récupération des contours de toutes les communes françaises au format shp : https://www.data.gouv.fr/fr/datasets/decoupage-administratif-communal-francais-issu-d-openstreetmap/
- dezip  du fichier shp.zip
- transformation du shp en mysql (http://www.gdal.org/ogr2ogr.html) : 'ogr2ogr -f MySQL MySQL:test,host=localhost,user=root communes-20170112.shp -nln commune -update -overwrite -lco engine=myisam -progress'. La BDD test contient la table commune avec les informations issues du fichier .shp
- extraction des communes du Grand-Nancy dans phpMyAdmin : SELECT insee as id_commune, nom as lib_commune, shape as geom_commune FROM `communes` WHERE insee in(54395, 54025, 54165, 54184, 54197, 54257, 54265, 54274, 54300, 54304,54328, 54339, 54357, 54439, 54482, 54495, 54498, 54526, 54547, 54578) 
- sous le résultat de l'extraction, clic sur "Créer une vue" > créer la vue en lui donnant comme nom "commune"
- ouvrir la vue commune dans phpMyAdmin et cliquer sur Exporter > Personnalisé > sélectionner  l'option "Exporter les vues comme les tables" 

Donne moi les codes INSEE des communes faisant partie de la comcom de Brive et je te donnerai le sql qui va bien pour les communes dans un premier temps.

A Brive, vous avez une seule entité qui gère la voirie ou bien c'est subdivisé en pôles comme à Toulouse (1 comcom divisé en 5 pôle territoriaux, cf http://velobs.2p2r.org/ > checkbox Limite des pôles)?

Si vous n'avez qu'un service, alors contours comcom = contours pôle, sinon, il faut déterminer le contour des pôles (voir s'il y a de l'open data sur Brive à ce sujet).

**Comment by PatriceLepissier** [comment]
J'ai réussi à récupérer la liste des communes et à les transférer vers le serveur mutualisé, mais uniquement après avoir installé un serveur apache et phpmyadmin sur mon PC (cela ne fonctionnait pas depuis des interfaces comme Emma ou MySQL Workbench). Il doit y avoir un problème avec l'encodage de l'export (UTF_8 ne doit pas être strictement identique pour tout le monde ...).
Je continue donc en tentant de récupérer les limites de l'agglo de Brive.
Merci pour l'aide.

**Comment by gerald2545** [comment]
Tu peux me donner ton mail STP. J'ai repris la doc de @ldesp pour la création des communes, des pôles et des territoires. Je t'enverrai le lien vers le mode opératoire.
ça devrait largement aider à la mise en route de velobs.
Pour les contours de Brive, du coup tu peux utiliser les codes INSEE sur https://fr.wikipedia.org/wiki/Communaut%C3%A9_d%27agglom%C3%A9ration_du_Bassin_de_Brive qui date de 2016, a doit être correct?

**Comment by gerald2545** [comment]
on a une doc qui a été testée par Sophia pour l'install : 
https://github.com/2p2r/velobs_web/tree/V1_4 + [velobs_geo.odt.pdf](https://github.com/2p2r/velobs_web/files/1480156/velobs_geo.odt.pdf)
si tu peux tester....

**Comment by gerald2545** [comment]
merci de rouvrir une issue en cas de problème. La doc citée dans le commentaire précédent est maintenant dans le fichier INSTALL.odt
